CPU: testbench.v CPU.v PC.v Registers.v Instruction_Memory.v Data_Memory.v And.v Adder.v ALU.v MUX32.v Sign_Extend.v Control.v ALU_Control.v IF_ID.v ID_EX.v EX_MEM.v MEM_WB.v
	iverilog -o CPU testbench.v CPU.v PC.v Registers.v Instruction_Memory.v Data_Memory.v And.v Adder.v ALU.v MUX32.v Sign_Extend.v Control.v ALU_Control.v IF_ID.v ID_EX.v EX_MEM.v MEM_WB.v
