CPU: testbench.v CPU.v PC.v Registers.v Instruction_Memory.v Data_Memory.v Adder.v ALU.v MUX32.v Sign_Extend.v Control.v ALU_Control.v IF_ID.v
	iverilog -o CPU testbench.v CPU.v PC.v Registers.v Instruction_Memory.v Data_Memory.v Adder.v ALU.v MUX32.v Sign_Extend.v Control.v ALU_Control.v IF_ID.v
